on:
  push:
    branches: [ master ]

name: Deploy to Amazon ECS

jobs:
  deploy:
    name: DeployS3
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ aws.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ aws.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-3
      - name: Build static site
        run: yarn install && npm run-script build
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://static-sites-vrma --delete
